BoxLayoutExample:


<BoxLayoutExample>:
    orientation:'vertical'
    Label: 
        text:"Press 'Open Camera' to access the camera"
        size_hint: 1,.3

    Button:
        text: "Open Camera"
        size_hint: .6,.05
        pos_hint: {"center_x": 0.5, "center_y":.9}
        width: "100dp" 
        on_press: root.on_open_camera_clicked()
    Label:
        text:""
        size_hint:1,0.1
        

